import os
import google.generativeai as genai
from graph.state import ResearchState


def _fmt(val, prefix="", suffix="", decimals=2):
    """Format a numeric value safely."""
    if val is None:
        return "N/A"
    try:
        if isinstance(val, float):
            return f"{prefix}{val:,.{decimals}f}{suffix}"
        return f"{prefix}{val:,}{suffix}"
    except Exception:
        return str(val)


def report_agent(state: ResearchState) -> ResearchState:
    """
    Agent 4 (Orchestrator synthesis): Uses Claude to synthesize all gathered data
    into a structured investment brief in markdown format.
    """
    ticker = state["ticker"]
    company_name = state["company_name"]
    market = state.get("market_data") or {}
    sentiment = state.get("sentiment_scores") or {}
    articles = state.get("news_articles") or []

    print(f"[ReportAgent] Synthesizing investment brief for {company_name}...")

    # Build a rich context block for Claude
    market_summary = f"""
MARKET DATA:
- Current Price: {_fmt(market.get('current_price'), prefix='$')} {market.get('currency', 'USD')}
- Market Cap: {_fmt(market.get('market_cap'), prefix='$')}
- P/E Ratio (TTM): {_fmt(market.get('pe_ratio'))}
- Forward P/E: {_fmt(market.get('forward_pe'))}
- EPS: {_fmt(market.get('eps'), prefix='$')}
- 52-Week High: {_fmt(market.get('52w_high'), prefix='$')}
- 52-Week Low: {_fmt(market.get('52w_low'), prefix='$')}
- Beta: {_fmt(market.get('beta'))}
- Dividend Yield: {_fmt(market.get('dividend_yield'), suffix='%')}
- Profit Margin: {_fmt(market.get('profit_margin'), suffix='%')}
- Return on Equity: {_fmt(market.get('return_on_equity'), suffix='%')}
- Debt to Equity: {_fmt(market.get('debt_to_equity'))}
- Analyst Recommendation: {market.get('analyst_recommendation', 'N/A').upper()}
- Analyst Price Target: {_fmt(market.get('target_price'), prefix='$')}
- Sector: {market.get('sector', 'N/A')}
- Industry: {market.get('industry', 'N/A')}
"""

    sentiment_summary = f"""
SENTIMENT ANALYSIS (from {len(articles)} recent news articles):
- Overall Sentiment: {sentiment.get('overall', 'N/A').upper()}
- Sentiment Score: {sentiment.get('score', 0.0)} (scale: -1.0 bearish to +1.0 bullish)
- Confidence: {sentiment.get('confidence', 'N/A')}
- Key Themes: {', '.join(sentiment.get('key_themes', []))}
- Identified Risks: {', '.join(sentiment.get('risks', []))}
- Identified Catalysts: {', '.join(sentiment.get('catalysts', []))}
- Narrative: {sentiment.get('summary', '')}
"""

    news_headlines = "\nRECENT HEADLINES:\n"
    for a in articles[:5]:
        news_headlines += f"- [{a['source']}] {a['title']}\n"

    prompt = f"""You are a senior equity research analyst at a top investment bank. 
Write a professional investment brief for {company_name} ({ticker}) based on the data below.

{market_summary}
{sentiment_summary}
{news_headlines}

Write the report in clean markdown with the following sections:

# {company_name} ({ticker}) — Investment Brief

## Executive Summary
(3-4 sentence overview: current situation, key thesis, recommendation)

## Company Snapshot
(Sector, industry, key business description in 2-3 sentences)

## Financial Highlights
(Table or bullet points of key metrics: price, P/E, market cap, margins, etc.)

## Sentiment & News Analysis
(What the news flow tells us. Key themes, risks, and catalysts identified.)

## Technical Overview
(Price vs 52-week range, analyst targets, momentum)

## Risk Factors
(3-5 specific risks for this company right now)

## Investment Thesis
(Bull case vs Bear case, each in 2-3 sentences)

## Recommendation
(Clear stance: BUY / HOLD / SELL with a short rationale and a 12-month price target estimate)

---
*Report generated by Multi-Agent Financial Research System | Data: yFinance, NewsAPI, Claude AI*

Write in a professional, confident tone. Use specific data points. Be direct."""

    try:
        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        model = genai.GenerativeModel("gemini-2.0-flash")
        response = model.generate_content(prompt)
        report = response.text
        print(f"[ReportAgent] Report generated ({len(report)} chars).")
        return {
            **state,
            "final_report": report,
            "current_step": "complete",
        }
    except Exception as e:
        errors = state.get("errors") or []
        fallback = f"# {company_name} ({ticker}) — Investment Brief\n\n**Error generating report:** {str(e)}\n\nPlease check your GEMINI_API_KEY."
        return {
            **state,
            "final_report": fallback,
            "errors": errors + [f"ReportAgent error: {str(e)}"],
            "current_step": "complete",
        }
